[build-system]
requires = [
  "hatchling",
  "oldest-supported-numpy",
]
build-backend = "hatchling"

[project]
name = "MiLoMerge"
version = "1.0.0"
authors = [
  { name="MiLoMerge authors", email="milomerg@lists.jh.edu"},
]
maintainers = [
  { name="MiLoMerge authors", email="milomerg@lists.jh.edu"},
]
description = "A package to take a given distribution and retrieve the best binning to maximize separation"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "h5py>=3.0.0",
  "numba>=0.63.1",
  "numpy>=2.0.0",
  "tqdm",
]

[project.urls]
"Github" = "https://github.com/MohitS704/bin_merging"
Homepage = "https://spin.pha.jhu.edu/"
Discussions = "https://github.com/MohitS704/bin_merging/discussions"
Changelog = "https://github.com/MohitS704/bin_merging/releases"

[project.optional-dependencies]
docs = [
  "furo",
  "myst_parser >=0.13",
  "sphinx >=4.0",
  "sphinx-copybutton",
  "sphinx-autodoc-typehints",
]
test = [
  "pytest"
]

[tool.hatch.build.targets.sdist]
include = [
  "src",
  "tests",
]
exclude = [
  "docs",
]