[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "MiLoMerge"
version = "1.0.0"
authors = [
  { name="Mohit Srivastav", email="msrivas6@jhu.edu"},
  { name="Michalis Panagiotou", email=""},
  { name="Lucas Kang", email="" },
]
maintainers = [
  { name="Mohit Srivastav", email="msrivas6@jhu.edu"},
  { name="Michalis Panagiotou", email=""},
  { name="Lucas Kang", email="" },
]
description = "A package to take a given distribution and retrieve the best binning to maximize separation"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Github" = "https://github.com/MohitS704/bin_merging"
